name: say-hello # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Say Hello World  # 79 char long summary
description: |
  This is hello-snap's description.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  say-hello:
    plugin: python
    source: .

apps:
  say-hello:
    command: bin/hello
